---
title: Annotation of ATAC (ASTARR Input) 12
subtitle: Arrange region pairs (Hi-C)
format:
    html:
        code-fold:  true 
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity: singularity_proj_encode_fcc
BASE DIRECTORY (FD_BASE): /data/reddylab/Kuei
REPO DIRECTORY (FD_REPO): /data/reddylab/Kuei/repo
WORK DIRECTORY (FD_WORK): /data/reddylab/Kuei/work
DATA DIRECTORY (FD_DATA): /data/reddylab/Kuei/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/log
PROJECT REF     (FD_REF): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/references

**Set global variables**

In [2]:
txt_fdiry = file.path(FD_RES, "region", "summary")
vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

metadata.label.astarr_macs_merge.tsv
metadata.label.chipseq_histone.tsv
metadata.label.chipseq_subset.tsv
metadata.label.chipseq_tf_full.tsv
metadata.label.hic.tsv
metadata.label.main.tsv
metadata.label.ocr.tsv
metadata.label.region_for_analysis.tsv

In [3]:
TXT_FDIRY_REGION_LABEL   = file.path(FD_RES, "region", "summary")
TXT_FNAME_REGION_LABEL_A = "metadata.label.astarr_macs_merge.tsv"
TXT_FNAME_REGION_LABEL_B = "metadata.label.hic.tsv"

## Import data

In [4]:
txt_fdiry = TXT_FDIRY_REGION_LABEL
txt_fname = TXT_FNAME_REGION_LABEL_A
txt_fpath = file.path(txt_fdiry, txt_fname)

dat_region_label_A = read_tsv(txt_fpath, show_col_types = FALSE)
dat_region_label_A

  Folder
1 fcc_astarr_macs_merge
2 fcc_astarr_macs_merge
  FName
1 K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz
2 K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz
  Label
1 fcc_astarr_macs_input_overlap
2 fcc_astarr_macs_input_union
  FPath
1 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/fcc_astarr_macs_merge/K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz
2 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/fcc_astarr_macs_merge/K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz

In [5]:
txt_fdiry = TXT_FDIRY_REGION_LABEL
txt_fname = TXT_FNAME_REGION_LABEL_B
txt_fpath = file.path(txt_fdiry, txt_fname)

dat_region_label_B = read_tsv(txt_fpath, show_col_types = FALSE)
dat_region_label_B

  Folder                      FName
1 hic_insitu_K562_ENCSR545YBD K562.hg38.hic_insitu.Loop_A.bed.gz
2 hic_insitu_K562_ENCSR545YBD K562.hg38.hic_insitu.Loop_B.bed.gz
3 hic_insitu_K562_ENCSR545YBD K562.hg38.hic_insitu.TAD.bed.gz
4 hic_intact_K562_deep        K562.hg38.hic_intact.Loop_A.bed.gz
5 hic_intact_K562_deep        K562.hg38.hic_intact.Loop_B.bed.gz
6 hic_intact_K562_ENCSR479XDG K562.hg38.hic_intact.Loop_A.bed.gz
7 hic_intact_K562_ENCSR479XDG K562.hg38.hic_intact.Loop_B.bed.gz
8 hic_intact_K562_ENCSR479XDG K562.hg38.hic_intact.TAD.bed.gz
  Label
1 hic_insitu_Loop_A_ENCSR545YBD
2 hic_insitu_Loop_B_ENCSR545YBD
3 hic_insitu_TAD_ENCSR545YBD
4 hic_intact_Loop_A_deep
5 hic_intact_Loop_B_deep
6 hic_intact_Loop_A_ENCSR479XDG
7 hic_intact_Loop_B_ENCSR479XDG
8 hic_intact_TAD_ENCSR479XDG
  FPath
1 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_insitu_K562_ENCSR545YBD/K562.hg38.hic_insitu.Loop_A.bed.gz
2 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_insitu_K562_ENCSR545YBD/K562.hg38.hic_insitu.Loop_B.bed.gz
3 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_insitu_K562_ENCSR545YBD/K562.hg38.hic_insitu.TAD.bed.gz
4 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_intact_K562_deep/K562.hg38.hic_intact.Loop_A.bed.gz
5 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_intact_K562_deep/K562.hg38.hic_intact.Loop_B.bed.gz
6 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_intact_K562_ENCSR479XDG/K562.hg38.hic_intact.Loop_A.bed.gz
7 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_intact_K562_ENCSR479XDG/K562.hg38.hic_intact.Loop_B.bed.gz
8 /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/hic_intact_K562_ENCSR479XDG/K562.hg38.hic_intact.TAD.bed.gz

**Check colnumn names**

In [6]:
dat = dat_region_label_A
vec = unique(dat$Folder)
vec_txt_region_folder_A = vec

for (txt_region_folder_A in vec_txt_region_folder_A){
    ### get column names for region A
    txt_fdiry = file.path(FD_RES, "region", txt_region_folder_A, "summary")
    txt_fname = "description.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)
    dat_cname = read_tsv(txt_fpath, show_col_types = FALSE)
    vec_txt_cname_A = dat_cname$Name

    ### show results
    cat(txt_region_folder_A, "\n")
    print(vec_txt_cname_A)
    cat("\n")
}

fcc_astarr_macs_merge
[1] "Chrom"      "ChromStart" "ChromEnd"   "Region"

In [7]:
dat = dat_region_label_B
vec = unique(dat$Folder)
vec_txt_region_folder_B = vec

for (txt_region_folder_B in vec_txt_region_folder_B){
    ### get column names for region B
    txt_fdiry = file.path(FD_RES, "region", txt_region_folder_B, "summary")
    txt_fname = "description.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)
    dat_cname = read_tsv(txt_fpath, show_col_types = FALSE)
    vec_txt_cname_B = dat_cname$Name

    ### show results
    cat(txt_region_folder_B, "\n")
    print(vec_txt_cname_B)
    cat("\n")
}

hic_insitu_K562_ENCSR545YBD
[1] "Chrom"      "ChromStart" "ChromEnd"   "Name"       "Group"
[6] "Label"

hic_intact_K562_deep
[1] "Chrom"      "ChromStart" "ChromEnd"   "Name"       "Group"
[6] "Label"

hic_intact_K562_ENCSR479XDG
[1] "Chrom"      "ChromStart" "ChromEnd"   "Name"       "Group"
[6] "Label"

## Read region intersections and arrange tables

**init of loop**

In [8]:
dat = dat_region_label_A
lst = split(dat, 1:nrow(dat))
lst = lapply(lst, as.list)

lst_region_label_A = lst
lst

$`1`
$`1`$Folder
[1] "fcc_astarr_macs_merge"

$`1`$FName
[1] "K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz"

$`1`$Label
[1] "fcc_astarr_macs_input_overlap"

$`1`$FPath
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/fcc_astarr_macs_merge/K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz"


$`2`
$`2`$Folder
[1] "fcc_astarr_macs_merge"

$`2`$FName
[1] "K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz"

$`2`$Label
[1] "fcc_astarr_macs_input_union"

$`2`$FPath
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/fcc_astarr_macs_merge/K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz"

In [9]:
dat = dat_region_label_B
vec = unique(dat$Folder)

vec_txt_region_folder_B = vec
for(txt in vec){cat(txt, "\n")}

hic_insitu_K562_ENCSR545YBD
hic_intact_K562_deep
hic_intact_K562_ENCSR479XDG

**Loop and arrange each region pair intersect table**

In [10]:
### loop through region A
for (idx in seq_along(lst_region_label_A)){
    
    ### get region A
    lst = lst_region_label_A[[idx]]
    txt_region_folder_A = lst$Folder
    txt_region_label_A  = lst$Label

    ### get column names for region A
    txt_fdiry = file.path(FD_RES, "region", txt_region_folder_A, "summary")
    txt_fname = "description.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)
    dat_cname = read_tsv(txt_fpath, show_col_types = FALSE)
    vec_txt_cname_A = dat_cname$Name

    ### loop through region B
    for (txt_region_folder_B in vec_txt_region_folder_B){
        
        ### get column names for region B
        txt_fdiry = file.path(FD_RES, "region", txt_region_folder_B, "summary")
        txt_fname = "description.tsv"
        txt_fpath = file.path(txt_fdiry, txt_fname)
        dat_cname = read_tsv(txt_fpath, show_col_types = FALSE)
        vec_txt_cname_B = dat_cname$Name

        ### get total column names for annotation table
        vec_txt_cname = c(
            paste0(vec_txt_cname_A, "_A"),
            paste0(vec_txt_cname_B, "_B"),
            "Overlap"
        )
        
        ### get directory of annotation table
        txt_fdiry = file.path(
            FD_RES, 
            "region_annotation",
            txt_region_label_A, 
            txt_region_folder_B
        )
        txt_fname = "*bed.gz"
        txt_fglob = file.path(txt_fdiry, txt_fname)

        ### get annotation table files
        vec_txt_fpath = Sys.glob(txt_fglob)
        vec_txt_fname = basename(vec_txt_fpath)

        ### show progress
        cat("===========================================\n")
        cat("Read annotation...", "\n")
        cat("Region A:", txt_region_folder_A, "|", txt_region_label_A, "\n")
        cat("Region B:", txt_region_folder_B, "\n")
        cat("FDiry:   ", "\n")
        print(txt_fdiry)
        cat("FName:   ", "\n")
        print(vec_txt_fname)
        cat("\n")
        flush.console()
        
        ### import annotation tables
        lst = lapply(vec_txt_fname, function(txt_fname){
            ### set directory
            txt_fpath = file.path(txt_fdiry, txt_fname)
            
            ### get annotation of region A and region B
            vec = str_split(txt_fname, "\\.")[[1]]
            txt_annot_A = vec[1]
            txt_annot_B = vec[2]

            ### read table and add annotation labels
            dat = read_tsv(txt_fpath, col_names = vec_txt_cname, show_col_types = FALSE)
            dat = dat %>% 
                dplyr::mutate(
                    Region_A = fun_gen_region(Chrom_A, ChromStart_A, ChromEnd_A),
                    Region_B = fun_gen_region(Chrom_B, ChromStart_B, ChromEnd_B),
                    Annotation_A = txt_annot_A,
                    Annotation_B = txt_annot_B
                )
            return(dat)
        }) 

        ### concatenate tables and assign
        dat = bind_rows(lst)
        dat_region_annot_pair = dat
        
        ### summarize annotation tables
        dat = dat_region_annot_pair
        dat = dat %>%
            dplyr::group_by(
                Chrom_A, ChromStart_A, ChromEnd_A, Region_A,
                Annotation_A,
                Annotation_B,
                Group_B,
                Label_B
            ) %>%
            dplyr::summarise(
                Region_Annot = paste(Region_B, collapse=";"),
                Region_Count = n(),
                .groups = "drop")

        ### rename the columns and assign
        colnames(dat) = c(
            "Chrom", "ChromStart", "ChromEnd", "Region", 
            "Annotation_A", 
            "Annotation_B",
            "Group",
            "Label",
            "Region_Annot",
            "Region_Count"
        )
        dat_region_annot_summary = dat

        ### set directory
        txt_fdiry = file.path(
            FD_RES, 
            "region_annotation",
            txt_region_label_A,
            "summary"
        )
        txt_fname1 = paste("region", "intersect", "pair",    txt_region_folder_B, "tsv", sep = ".")
        txt_fpath1 = file.path(txt_fdiry, txt_fname1)
        txt_fname2 = paste("region", "intersect", "summary", txt_region_folder_B, "tsv", sep = ".")
        txt_fpath2 = file.path(txt_fdiry, txt_fname2)
        
        ### show progress
        cat("Save annotation...",  "\n")
        cat("FDiry: ", txt_fdiry, "\n")
        cat("FName1:", txt_fname1, "\n")
        cat("FName2:", txt_fname2, "\n")
        cat("\n")
        flush.console()

        ### write tables
        dir.create(txt_fdiry, showWarnings = FALSE)
        write_tsv(dat_region_annot_pair,    txt_fpath1)
        write_tsv(dat_region_annot_summary, txt_fpath2)
    } ### end loop region B
} ### end loop region A

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_overlap
Region B: hic_insitu_K562_ENCSR545YBD
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/hic_insitu_K562_ENCSR545YBD"
FName:
[1] "fcc_astarr_macs_input_overlap.hic_insitu_Loop_A_ENCSR545YBD.bed.gz"
[2] "fcc_astarr_macs_input_overlap.hic_insitu_Loop_B_ENCSR545YBD.bed.gz"
[3] "fcc_astarr_macs_input_overlap.hic_insitu_TAD_ENCSR545YBD.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/summary
FName1: region.intersect.pair.hic_insitu_K562_ENCSR545YBD.tsv
FName2: region.intersect.summary.hic_insitu_K562_ENCSR545YBD.tsv

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_overlap
Region B: hic_intact_K562_deep
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/hic_intact_K562_deep"
FName:
[1] "fcc_astarr_macs_input_overlap.hic_intact_Loop_A_deep.bed.gz"
[2] "fcc_astarr_macs_input_overlap.hic_intact_Loop_B_deep.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/summary
FName1: region.intersect.pair.hic_intact_K562_deep.tsv
FName2: region.intersect.summary.hic_intact_K562_deep.tsv

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_overlap
Region B: hic_intact_K562_ENCSR479XDG
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/hic_intact_K562_ENCSR479XDG"
FName:
[1] "fcc_astarr_macs_input_overlap.hic_intact_Loop_A_ENCSR479XDG.bed.gz"
[2] "fcc_astarr_macs_input_overlap.hic_intact_Loop_B_ENCSR479XDG.bed.gz"
[3] "fcc_astarr_macs_input_overlap.hic_intact_TAD_ENCSR479XDG.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_overlap/summary
FName1: region.intersect.pair.hic_intact_K562_ENCSR479XDG.tsv
FName2: region.intersect.summary.hic_intact_K562_ENCSR479XDG.tsv

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_union
Region B: hic_insitu_K562_ENCSR545YBD
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/hic_insitu_K562_ENCSR545YBD"
FName:
[1] "fcc_astarr_macs_input_union.hic_insitu_Loop_A_ENCSR545YBD.bed.gz"
[2] "fcc_astarr_macs_input_union.hic_insitu_Loop_B_ENCSR545YBD.bed.gz"
[3] "fcc_astarr_macs_input_union.hic_insitu_TAD_ENCSR545YBD.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/summary
FName1: region.intersect.pair.hic_insitu_K562_ENCSR545YBD.tsv
FName2: region.intersect.summary.hic_insitu_K562_ENCSR545YBD.tsv

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_union
Region B: hic_intact_K562_deep
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/hic_intact_K562_deep"
FName:
[1] "fcc_astarr_macs_input_union.hic_intact_Loop_A_deep.bed.gz"
[2] "fcc_astarr_macs_input_union.hic_intact_Loop_B_deep.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/summary
FName1: region.intersect.pair.hic_intact_K562_deep.tsv
FName2: region.intersect.summary.hic_intact_K562_deep.tsv

===========================================
Read annotation...
Region A: fcc_astarr_macs_merge | fcc_astarr_macs_input_union
Region B: hic_intact_K562_ENCSR479XDG
FDiry:
[1] "/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/hic_intact_K562_ENCSR479XDG"
FName:
[1] "fcc_astarr_macs_input_union.hic_intact_Loop_A_ENCSR479XDG.bed.gz"
[2] "fcc_astarr_macs_input_union.hic_intact_Loop_B_ENCSR479XDG.bed.gz"
[3] "fcc_astarr_macs_input_union.hic_intact_TAD_ENCSR479XDG.bed.gz"

Save annotation...
FDiry:  /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region_annotation/fcc_astarr_macs_input_union/summary
FName1: region.intersect.pair.hic_intact_K562_ENCSR479XDG.tsv
FName2: region.intersect.summary.hic_intact_K562_ENCSR479XDG.tsv