---
title: FCC coverage vs ENCODE cCREs/ChromHMM 02
subtitle: Calculate mean and estimate its standard errors by bootstrapping
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity: singularity_proj_encode_fcc
BASE DIRECTORY (FD_BASE): /data/reddylab/Kuei
REPO DIRECTORY (FD_REPO): /data/reddylab/Kuei/repo
WORK DIRECTORY (FD_WORK): /data/reddylab/Kuei/work
DATA DIRECTORY (FD_DATA): /data/reddylab/Kuei/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/log
PROJECT REF     (FD_REF): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/references

**Set global variable**

In [2]:
vec = c(
    "fcc_astarr_macs_input_overlap",
    "fcc_astarr_macs_input_union"
)
names(vec) = vec

VEC_TXT_FOLDER = vec
for(txt in vec){cat(txt, "\n")}

fcc_astarr_macs_input_overlap
fcc_astarr_macs_input_union

**View files**

In [3]:
txt_folder = VEC_TXT_FOLDER[1]
txt_fdiry  = file.path(FD_RES, "analysis_fcc_comparison", txt_folder)
txt_fname  = "region.annotation.encode_chromatin_states.coverage.fcc.tsv"
txt_fglob  = file.path(txt_fdiry, txt_fname)

vec = Sys.glob(txt_fglob)
for (txt in vec) {cat(txt, "\n")}

/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/analysis_fcc_comparison/fcc_astarr_macs_input_overlap/region.annotation.encode_chromatin_states.coverage.fcc.tsv

## Import data

In [4]:
### loop to import data
lst = lapply(VEC_TXT_FOLDER, function(txt_folder){
    ### set file directory
    txt_fdiry  = file.path(FD_RES, "analysis_fcc_comparison", txt_folder)
    txt_fname = "region.annotation.encode_chromatin_states.coverage.fcc.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)

    ### read table
    dat = read_tsv(txt_fpath, show_col_types = FALSE)
    return(dat)
})

### assign and show
lst_dat_region_merge_fcc_import = lst

res = lapply(lst, dim)
print(res)

dat = lst[[1]]
head(dat, 3)

$fcc_astarr_macs_input_overlap
[1] 1950396      13

$fcc_astarr_macs_input_union
[1] 2701904      13

  Chrom ChromStart ChromEnd Region           Group    Label     Score
1 chr1  10038      10405    chr1:10038-10405 cCREs    Low-DNase -2.23485265
2 chr1  10038      10405    chr1:10038-10405 ChromHMM Quies     -2.23485265
3 chr1  14282      14614    chr1:14282-14614 ChromHMM Quies      0.03179044
  Zcore      Score_Label Zcore_Label   Assay_Folder               Assay_Group
1 -3.5573621 Log2FC      Scale(Log2FC) STARR_ATAC_K562_Reddy_KS91 ASTARR_KS91
2 -3.5573621 Log2FC      Scale(Log2FC) STARR_ATAC_K562_Reddy_KS91 ASTARR_KS91
3  0.0361388 Log2FC      Scale(Log2FC) STARR_ATAC_K562_Reddy_KS91 ASTARR_KS91
  Assay_Label
1 ASTARR
2 ASTARR
3 ASTARR

**Check: Count table**

In [5]:
lst = lst_dat_region_merge_fcc_import
lst = lapply(lst, function(dat){
    res = table(dat$Group, dat$Assay_Label, dnn=c("Group", "Assay"))
    dat = as.data.frame(res)
    return(dat)
})

dat = bind_rows(lst, .id = "Folder")
dat = dat %>% tidyr::spread(Folder, Freq)
fun_display_table(dat)

Group,Assay,fcc_astarr_macs_input_overlap,fcc_astarr_macs_input_union
cCREs,ASTARR,193629,277308
cCREs,CRISPRi-Growth,121985,137396
cCREs,CRISPRi-HCRFF,1301,1715
cCREs,LMPRA,102220,116451
cCREs,TMPRA,1540,2057
cCREs,WSTARR,190911,273809
ChromHMM,ASTARR,220963,343431
ChromHMM,CRISPRi-Growth,124614,142592
ChromHMM,CRISPRi-HCRFF,1443,2015
ChromHMM,LMPRA,103530,118901
ChromHMM,TMPRA,1751,2508
ChromHMM,WSTARR,217104,337137
ChromHMM_Relabel,ASTARR,220963,343431
ChromHMM_Relabel,CRISPRi-Growth,124614,142592
ChromHMM_Relabel,CRISPRi-HCRFF,1443,2015
ChromHMM_Relabel,LMPRA,103530,118901
ChromHMM_Relabel,TMPRA,1751,2508
ChromHMM_Relabel,WSTARR,217104,337137

## Helper function

In [6]:
fun_bstrap_interveral = function(vec_num_score, fun = `mean`, num_iteration = 1000, num_seed = 123){
    ### init
    set.seed(num_seed)
    
    ### column: num_iteraction
    ### row:    length(vec_num)
    mat = replicate(
        num_iteration,
        sample(vec_num_score, replace = TRUE, size = 1000)
    )

    vec = apply(mat, 2, fun)
    res = quantile(vec, probs = c(0, 0.025, 0.25, 0.5, 0.75, 0.975, 1))
    res = c(res, mean(vec), length(vec_num_score))
    names(res) = c("Min", "Ci95_Lw", "Q1", "Q2", "Q3", "Ci95_Up", "Max", "Mean", "N")
    return(res)
}

## Run bootstrapping

In [7]:
lst = lst_dat_region_merge_fcc_import
lst = lapply(lst, function(dat){
    ### split data by each state
    lst = split(dat, dat$Assay_Label)
    
    ### run bootstrapping for each state
    lst = lapply(lst, function(dat){
        lst_inner = split(dat$Zcore, dat$Label)
        lst_inner = lapply(lst_inner, fun_bstrap_interveral)
        dat = bind_rows(lst_inner, .id = "Annot_Label")
        return(dat)
    })
    
    ### concat results
    dat = bind_rows(lst, .id = "Assay_Label")
    return(dat)
})

### assign and show
lst_dat_annot_score_summary = lst

res = lapply(lst, dim)
print(res)

dat = lst[[1]]
head(dat, 3)

$fcc_astarr_macs_input_overlap
[1] 204  11

$fcc_astarr_macs_input_union
[1] 204  11

  Assay_Label Annot_Label Min        Ci95_Lw    Q1        Q2         Q3
1 ASTARR      Active TSS   0.5546350  0.5984198  0.646910  0.6683370  0.6915949
2 ASTARR      Biv         -0.6259661 -0.5864678 -0.546476 -0.5291561 -0.5102939
3 ASTARR      Bivalent    -0.6259661 -0.5864678 -0.546476 -0.5291561 -0.5102939
  Ci95_Up    Max        Mean       N
1  0.7341674  0.8013775  0.6688214 10159
2 -0.4750851 -0.4084481 -0.5291286 12367
3 -0.4750851 -0.4084481 -0.5291286 12367

**Check: count number of assays for each group**

In [8]:
lst = lst_dat_annot_score_summary
dat = lst[[1]]
table(dat$Annot_Label)

           Active TSS                   Biv              Bivalent
                    6                     6                     6
              CA-CTCF            CA-H3K4me3               CA-only
                    6                     6                     6
                CA-TF                  dELS                  Enh1
                    6                     6                     6
                 Enh2              Enhancer      Enhancer in gene
                    6                     6                     6
                EnhG1                 EnhG2          Flanking TSS
                    6                     6                     6
                  Het       Heterochromatin             Low-DNase
                    6                     6                     6
                 pELS                   PLS                 Quies
                    6                     6                     6
            Quiescent Repressed by Polycomb                ReprPC
                    6                     6                     6
        Transcription                   Tss               TssFlnk
                    6                     6                     6
             TssFlnkD              TssFlnkU                    Tx
                    6                     6                     6
                 TxWk    Weak transcription     ZNF genes repeats
                    6                     6                     6
             ZNF/Rpts
                    6

## Export results

In [9]:
for (txt_folder in VEC_TXT_FOLDER){
    ### get tables
    dat_region_result = lst_dat_annot_score_summary[[txt_folder]]
    
    ### set file directory
    txt_fdiry  = file.path(FD_RES, "analysis_fcc_comparison", txt_folder)
    txt_fname = "result.comparison.encode_chromatin_states.coverage.fcc.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)

    ### write table
    dat = dat_region_result
    write_tsv(dat, txt_fpath)
}